entries:
- title:
  pdftitle: qumulo-nexus-configuration-guide.pdf
  product:
  version:
  folders:

  - title:
    output: pdf
    type: frontmatter
    folderitems:

    - title:
      url: /titlepage.html
      output: pdf
      type: frontmatter

    - title:
      url: /tocpage.html
      output: pdf
      type: frontmatter

  - title: Qumulo Nexus Configuration Guide
    output: web
    type: navi
    folderitems:

    - title: Documentation Home
      url: /index.html
      output: web

    - title: Guide Table of Contents
      url: /qumulo-nexus-configuration-guide/
      output: web

    - title: Contacting the Qumulo Care Team
      url: /contacting-qumulo-care-team.html
      output: web

  - title: Authentication in Qumulo Nexus
    url: /qumulo-nexus-configuration-guide/authentication/index.html
    output: web, pdf
    folderitems:    

    - title: Enabling Single Sign-On (SSO) for Storage Administrators
      url: /qumulo-nexus-configuration-guide/authentication/enabling-sso-with-idp-storage-administrator-workflow.html
      output: web, pdf

    - title: Enabling Single Sign-On (SSO) for System Administrators
      url: /qumulo-nexus-configuration-guide/authentication/enabling-sso-with-idp-system-administrator-workflow.html
      output: web, pdf

  - title: Authorization in Qumulo Nexus
    url: /qumulo-nexus-configuration-guide/authorization/index.html
    output: web, pdf
    folderitems:    

    - title: Managing User Access
      url: /qumulo-nexus-configuration-guide/authorization/managing-user-access.html
      output: web, pdf

  - title: Monitoring and Metrics
    url: /qumulo-nexus-configuration-guide/monitoring-and-metrics/index.html
    output: web, pdf
    folderitems:    

    - title: Enabling Nexus Remote Support and Nexus Remote Management
      url: /qumulo-nexus-configuration-guide/monitoring-and-metrics/enabling-nexus-remote-support-and-remote-management.html
      output: web, pdf
