destination: _site/
url: "http://127.0.0.1:4000"
baseurl: "/qumulo-doc"
port: 4000
output: pdf
#product: Qumulo Alerts Guide
print_title: Qumulo Integration Guide
#print_subtitle: Version 3.3.0
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true

pdf_sidebar: integration_guide_sidebar
