destination: _site/
url: "http://127.0.0.1:4001"
baseurl: "/qumulo-doc"
port: 4001
output: pdf
#product: Qumulo in the Cloud Guide
print_title: Azure Native Qumulo Scalable File Service Guide
#print_subtitle: version 6.0
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true

pdf_sidebar: azure_guide_sidebar
