name: Build production site
on:
  # For manual trigger
  workflow_dispatch:
    branches:
    - gh-pages
#  We don't need this to run on the live pages until we migrate this workflow
#  to doing the github pages generation
#  push:
#    branches:
#    - gh-pages
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # It is recommended to use specific versions
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - uses: ruby/setup-ruby@b256bd96bb4867e7d23e92e087d9bb697270b725  # v1.163.0
        with:
          ruby-version: '2.7'
          bundler-cache: true

      - name: Write JSON secret to file
        run: echo -n "${{ secrets.ENGINEERING_JSON }}" | base64 --decode > hot-topic/engineering-173019-49cb92815171.json

      - name: Build and run google-analytics-script Docker image
        run: |
          docker build -t google-analytics-script -f hot-topic/Dockerfile ./hot-topic
          docker run -v $(pwd)/hot-topic/engineering-173019-49cb92815171.json:/app/engineering-173019-49cb92815171.json \
                     -v $(pwd)/README.md:/app/README.md \
                     google-analytics-script

      # Currently, this action doesn't do anything
      - name: Build site
        # `prod` is the name of the output directory
        run: JEKYLL_ENV=preview LC_ALL=C.UTF-8 bundle exec jekyll build -d prod
