name: Build production site
on:
  # For manual trigger
  workflow_dispatch:
    branches:
    - gh-pages
#  We don't need this to run on the live pages until we migrate this workflow
#  to doing the github pages generation
#  push:
#    branches:
#    - gh-pages
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # It is recommended to use specific versions
      - uses: actions/checkout@v3.3.0
      - uses: actions/cache@v3.2.4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - uses: ruby/setup-ruby@ee26e27437bde475b19a6bf8cb73c9fa658876a2  # v1.134.0
        with:
          ruby-version: '2.7'
          bundler-cache: true
      # Currently, this action doesn't do anything
      - name: Build site
        # `prod` is the name of the output directory
        run: JEKYLL_ENV=preview LC_ALL=C.UTF-8 bundle exec jekyll build -d prod
