name: Regenerate documentation and push local gh-pages and mainline branches
on:
  push:
    branches:
      - mainline
permissions:
  contents: write
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ env.GITHUB_REF_NAME }}

      - name: Rebuild Hot Topics ranking in README.md, show deltas, and commit changes
        run: |
          ./tools/test-build-hot-topic.sh

          # Set credentials
          git config --global user.email "qontent@qumulo.com"
          git config --global user.name "Team Qontent"        

          # Show deltas
          git diff

          # Commit changes
          git add --all
          git commit -m "Regenerated README.md with Hot Topic ranking" || echo "No changes to commit" >&2
          
        env:
          ENGINEERING_JSON: ${{ secrets.ENGINEERING_JSON }}

      - name: Build common container
        run: ./tools/test-build-container.sh

      - name: Check spelling (non-fatal)
        run: |
          # Do not fail if the check throws an error
          set +e
          ./tools/test-spelling.sh
          
          # Capture the exit code  
          status=$?
          if [ $status -ne 0 ]; then
            echo "::warning::Fix spelling errors and add exceptions to tools/.spelling-allowlist"
          fi
          exit 0

      - name: Check scripts, links, and images (non-fatal)
        shell: bash {0} # Allow manual error handling 
        run: |
          # Do not fail if the check throws an error
          set +e
          ./tools/test-scripts-links-images.sh
          
          # Capture the exit code
          status=$?
          if [ $status -ne 0 ]; then
            echo "::warning::Fix script/link/image errors. 404s for unpublished pages is normal."
          fi
          exit 0

      - name: Rebuild documentation
        run: ./tools/test-build-html.sh

      - name: Commit documentation changes
        run: |
          git add --all
          git commit -m "Rebuilt documentation website" || echo "No changes to commit" >&2

      - name: Prepare SSH key
        run: |
          echo "${{ secrets.DOCS_PUBLISH_KEY }}" > /tmp/key
          chmod 400 /tmp/key

      - name: Push local gh-pages branch to remote gh-pages branch
        run: |
          git remote add -m gh-pages public git@github.com:Qumulo/docs
          git push --set-upstream public gh-pages
          git push --set-upstream public mainline
        env:
          GIT_SSH_COMMAND: ssh -i /tmp/key

      - name: Clean up SSH key
        run: |
          rm -f /tmp/key
        if: always()
