name: Build and push docs to prod
on:
  push:
    branches:
      - mainline

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ env.GITHUB_REF_NAME }}

      - name: Rebuild Hot Topics ranking in index.md, show deltas, and commit changes
        run: |
          ./tools/test-build-hot-topic.sh

          # Set credentials
          git config --global user.email "qontent@qumulo.com"
          git config --global user.name "Team Qontent"

          # Show deltas
          git diff

          # Commit changes
          git add --all
          git commit -m "Regenerated index.md with Hot Topic ranking" || echo "No changes to commit" >&2

        env:
          ENGINEERING_JSON: ${{ secrets.ENGINEERING_JSON }}

      - name: Build common container
        run: ./tools/test-build-container.sh

      - name: Check spelling (non-fatal)
        run: |
          # Do not fail if the check throws an error
          set +e
          ./tools/test-spelling.sh

          # Capture the exit code
          status=$?
          if [ $status -ne 0 ]; then
            echo "::warning::Fix spelling errors and add exceptions to tools/.spelling-allowlist"
          fi
          exit 0

      - name: Check scripts, links, and images (non-fatal)
        shell: bash {0} # Allow manual error handling
        run: |
          # Do not fail if the check throws an error
          set +e
          ./tools/test-scripts-links-images.sh

          # Capture the exit code
          status=$?
          if [ $status -ne 0 ]; then
            echo "::warning::Fix script/link/image errors. 404s for unpublished pages is normal."
          fi
          exit 0

      - name: Prepare ReadOnly SSH key - access to external repos we include
        run: |
          echo "${{ secrets.DOCS_READONLY_KEY }}" > /tmp/ro_key
          chmod 400 /tmp/ro_key

      - name: Build documentation and sitemap.xml. _site is ready for use
        run: |
          ./tools/test-build-html.sh
        env:
          GIT_SSH_COMMAND: ssh -i /tmp/ro_key

      - name: Checkout fresh copy of repo with gh-pages branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: gh-pages
          path: content

      - name: Sync and update the gh-pages branch
        run: |
          rsync -a _site/ content/

          git -C content add --all
          git -C content commit -m "Rebuilt documentation website" || echo "No changes to commit" >&2

          # Force push internal `gh-pages` branch to public `gh-pages` branch
          git -C content push --force gh-pages

      - name: Clean up SSH key
        run: |
          rm -f /tmp/ro_key
        if: always()

  push-to-public:
    if: ${{ github.repository == 'Qumulo/docs-internal' }}
    uses: ./.github/workflows/push-to-public.yml
