name: Build and validate docs
on:
  push:
    branches:
      - mainline
  repository_dispatch:
     types: [run-publish]

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}

      - name: Rebuild Hot Topics ranking in index.md, show deltas, and commit changes
        if: ${{ github.repository == 'Qumulo/docs-internal' }}
        run: |
          ./tools/test-build-hot-topic.sh

          # Set credentials
          git config --global user.email "qontent@qumulo.com"
          git config --global user.name "Team Qontent"

          # Show deltas
          git diff

          # Commit changes
          git add --all
          git commit -m "Regenerated index.md with Hot Topic ranking" || echo "No changes to commit" >&2

        env:
          ENGINEERING_JSON: ${{ secrets.ENGINEERING_JSON }}

      - name: Build common container
        run: ./tools/test-build-container.sh

      - name: Prepare ReadOnly SSH key - access to external repos we include
        if: ${{ github.repository == 'Qumulo/docs-internal' }}
        run: |
          echo "${{ secrets.DOCS_READONLY_KEY }}" > /tmp/ro_key
          chmod 400 /tmp/ro_key

      - name: Build documentation and sitemap.xml. _site is ready for use
        run: |
          ./tools/test-build-html.sh
        env:
          GIT_SSH_COMMAND: ssh -i /tmp/ro_key
          EXTERNAL_REPOS: ${{ vars.EXTERNAL_REPOS }}

      - name: Sync and update the gh-pages branch
        env:
          GIT_ACTOR: ${{ github.actor }}
          IS_INTERNAL: ${{ github.repository == 'Qumulo/docs-internal' }}
        run: ./tools/sync-gh-pages.sh

      - name: Clean up SSH key
        if: ${{ github.repository == 'Qumulo/docs-internal' }}
        run: |
          rm -f /tmp/ro_key

  push-to-public:
    if: ${{ github.repository == 'Qumulo/docs-internal' }}
    secrets: inherit # pass all secrets
    needs: publish
    uses: ./.github/workflows/push-to-public.yml

  notify-docs-internal:
    if: ${{ github.repository != 'Qumulo/docs-internal' }}
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: Notify docs-internal repository of update in the current repository
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.REPO_PAT }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/Qumulo/docs-internal/dispatches \
            -d '{"event_type":"run-publish"}'
