name: Build feature branch
on:
  # Manual trigger for feature branch
  workflow_dispatch:
    branches-ignore:
    - gh-pages
  # Push trigger for feature branch
  push:
    branches-ignore:
    - gh-pages
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # It is recommended to use specific versions
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - uses: ruby/setup-ruby@b256bd96bb4867e7d23e92e087d9bb697270b725  # v1.163.0
        with:
          ruby-version: '2.7'
          bundler-cache: true
      # This action builds the feature branch ephemerally
      # to prove that nothing is broken
      - name: Build feature branch
        # `prod` is the name of the output directory
        run: JEKYLL_ENV=preview LC_ALL=C.UTF-8 bundle exec jekyll build -d test
