name: Test docs feature branch
on:
  # Manual trigger for feature branch
  workflow_dispatch:
    branches-ignore:
      - gh-pages
  # Push trigger for feature branch
  push:
    branches-ignore:
      - gh-pages
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # It is recommended to use specific versions
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ env.GITHUB_REF_NAME }}

      - name: Rebuild Hot Topics ranking in index.md and show deltas (dry run)
        run: |
          ./tools/test-build-hot-topic.sh

          # Show deltas
          git diff

          # Revert changes before switching branches
          git reset --hard ${{ env.GITHUB_REF_NAME }}
        env:
          ENGINEERING_JSON: ${{ secrets.ENGINEERING_JSON }}

      - name: Build common container
        run: ./tools/test-build-container.sh

      - name: Check spelling (non-fatal)
        run: |
          # Do not fail if the check throws an error
          set +e
          ./tools/test-spelling.sh

          # Capture the exit code  
          status=$?
          if [ $status -ne 0 ]; then
            echo "::warning::Fix spelling errors and add exceptions to tools/.spelling-allowlist"
          fi
          exit 0

      - name: Check scripts, links, and images (non-fatal)
        shell: bash {0} # Allow manual error handling 
        run: |
          # Do not fail if the check throws an error
          set +e
          ./tools/test-scripts-links-images.sh

          # Capture the exit code
          status=$?
          if [ $status -ne 0 ]; then
            echo "::warning::Fix script/link/image errors. 404s for unpublished pages is normal."
          fi
          exit 0

      - name: Rebuild documentation (dry run)
        run: ./tools/test-build-html.sh --dry-run
